CREATE DATABASE [Airport]
USE [Airport]

CREATE TABLE [Passengers](
	[Id] INT PRIMARY KEY IDENTITY,
	[FullName] VARCHAR(100) NOT NULL,
	[Email] VARCHAR(50) NOT NULL
)

CREATE TABLE [Pilots](
	[Id] INT PRIMARY KEY IDENTITY,
	[FirstName] VARCHAR(30) NOT NULL,
	[LastName] VARCHAR(30) NOT NULL,
	[Age] TINYINT NOT NULL,
	[Rating] FLOAT --!!!!!!!!!!!!
)

CREATE TABLE [AircraftTypes](
	[Id] INT PRIMARY KEY IDENTITY,
	[TypeName] VARCHAR(30) NOT NULL
)

CREATE TABLE [Aircraft](
	[Id] INT PRIMARY KEY IDENTITY,
	[Manufacturer] VARCHAR(25) NOT NULL,
	[Model] VARCHAR(30) NOT NULL,
	[Year] INT NOT NULL,
	[FlightHours] INT,
	[Condition] CHAR(1) NOT NULL,
	[TypeId] INT FOREIGN KEY REFERENCES [AircraftTypes] NOT NULL
)

CREATE TABLE [PilotsAircraft](
	[AircraftId] INT FOREIGN KEY REFERENCES [Aircraft] NOT NULL,
	[PilotId] INT FOREIGN KEY REFERENCES [Pilots] NOT NULL,
	PRIMARY KEY([AircraftId], [PilotId])
)

CREATE TABLE [Airports](
	[Id] INT PRIMARY KEY IDENTITY,
	[AirportName] VARCHAR(70) NOT NULL,
	[Country] VARCHAR(100) NOT NULL
)

CREATE TABLE [FlightDestinations](
	[Id] INT PRIMARY KEY IDENTITY,
	[AirportId] INT FOREIGN KEY REFERENCES [Airports] NOT NULL,
	[Start] DATETIME NOT NULL,
	[AircraftId] INT FOREIGN KEY REFERENCES [Aircraft] NOT NULL,
	[PassengerId] INT FOREIGN KEY REFERENCES [Passengers] NOT NULL,
	[TicketPrice] DECIMAL(18,2) DEFAULT 15 NOT NULL
)